[project]
name = "agio-publish-simple"
version = "0.0.16"
requires-python = ">=3.11"
license = "MIT"

dependencies = [
    "frame-stamp>=0.1.12",
    "pyside6>=6.10.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"agio_publish_simple" = [
    "__agio__.yml",
    "resources/**"
]
